name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up SSH key (debugging)
        run: |
          set -e
          mkdir -p ~/.ssh
          echo "🛠 Carpeta .ssh creada"
          
          printf "%b" "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa || { echo '❌ Falló printf'; exit 1; }
          echo "✅ Llave escrita"

          chmod 700 ~/.ssh || { echo '❌ Falló chmod 700'; exit 1; }
          chmod 600 ~/.ssh/id_rsa || { echo '❌ Falló chmod 600'; exit 1; }
          echo "✅ Permisos asignados"

          ssh-keyscan -H 40.233.24.40 >> ~/.ssh/known_hosts || { echo '❌ Falló ssh-keyscan'; exit 1; }
          echo "✅ ssh-keyscan completado"
          
          ls -l ~/.ssh
          echo "📄 Contenido de id_rsa:"
          head -n 5 ~/.ssh/id_rsa
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}


      - name: Build project
        run: npm install && npm run build

      - name: Deploy via SCP
        run: scp -r dist/* ${{ secrets.SERVER_ROUTE }}
